# Generated by Django 5.2.8 on 2025-11-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleCrud', '0002_alter_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_type',
            field=models.CharField(choices=[('Two Wheelers', 'Two Wheelers'), ('Three Wheelers', 'Three Wheelers'), ('Four Wheelers', 'Four Wheelers')], max_length=25),
        ),
    ]
